### ISSUE TITLE
Add inactivity timeout after two unanswered questions.

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-bionic-eyes-quiz-show#29]
Quiz should timeout and return to the attract screen when no one has answered any questions for 2 questions.

This addresses the scenario when people stand up and walk away in the middle of the quiz. We don't want the quiz to continue with no one actively using it.

**Comment by abdulrauf11** [comment]
Do we show this somewhere visually or not? Should the app restart automatically if nobody answers 2 consecutive questions?

**Comment by abdulrauf11** [comment]
Also, should the app just refresh, or do we jump to the next quiz? It will go to the attract screen in both cases.

**Comment by tnordberg** [comment]
@abdulrauf11 No, there's no need to represent/warn this visually, and you can just refresh the app in this case.

Here is an example scenario:

1. Group sits down and begins quiz
2. After answering Questions `1`, `2`, and `3`, the group stands up and leaves
3. Question `4` concludes with no input
4. Question `5` concludes with no input
5. App recognizes two questions have gone unanswered, and immediately refreshes to attract screen. 

[Edit for formatting]
