### ISSUE TITLE
Question screen videos should loop 

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-bionic-eyes-quiz-show#30]
This is a change from what we previously requested.

All videos used on the Question screen should now loop by default. We will edit certain videos to be longer so they never reach the end of the video.

**Comment by abdulrauf11** [comment]
@tnordberg  Are you talking about the videos that are a part of the question? I've attached one as an example below.

<img width="1469" alt="Screenshot 2022-01-11 at 2 53 54 AM" src="https://user-images.githubusercontent.com/26784406/148845133-24172c75-b3cf-4366-a60c-e54e74df1192.png">

**Comment by tnordberg** [comment]
@abdulrauf11 yes, these are the videos that should loop. Thanks.
