### ISSUE TITLE
Design changes and adjustments (see PDF)

### ISSUE THREAD

**Issue by tnordberg** [scimusmn/tsck-bionic-eyes-quiz-show#31]
Our designer compiled a list of changes and adjustments with screenshots in the PDF:

[Programmer Feedback Review.01.02.21.pdf](https://github.com/scimusmn/tsck-bionic-eyes-quiz-show/files/7831568/Programmer.Feedback.Review.01.02.21.pdf)

Let me know if you'd like me to break these into individual issues. I can pass along any clarification questions you have after looking through the PDF.

**Comment by abdulrauf11** [comment]
Hi @tnordberg, can you please confirm if this is correct? Previously we've used a video background for this.

<img width="926" alt="Screenshot 2022-01-19 at 3 55 23 PM" src="https://user-images.githubusercontent.com/26784406/150116551-6ac45446-ce5f-412b-a6c3-87a24c831c7a.png">

**Comment by tnordberg** [comment]
@abdulrauf11 this is our mistake. Our designer didn't know the gradient was part of the video. 

My understanding is that this is currently a fullscreen background video that my team created, correct? If so, leave it as a video and I will make sure they understand we need to update the video with the correct gradient.

**Comment by abdulrauf11** [comment]
Yes, it is a full-screen background video. If you just want to use a static gradient, I can also remove the video and add that. Let me know what you want to do?

**Comment by tnordberg** [comment]
@abdulrauf11 thanks for offering this option. We decided we will no longer plan to make a video background, so go ahead and swap in a static gradient in place of the video. 

I will be sending a couple other requests tomorrow, but wanted to let you know about this change first. Thanks!
